"""Task splitting engine for multi-agent collaboration."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Any

from openharness.api.client import SupportsStreamingMessages, ApiMessageRequest
from openharness.engine.messages import ConversationMessage, TextBlock
from openharness.swarm.shared_context import SharedContext
from openharness.swarm.structured_message import TaskStatus


@dataclass
class SubTask:
    """A sub-task generated by the TaskSplitter."""

    task_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    description: str = ""
    dependencies: list[str] = field(default_factory=list)
    context_refs: list[str] = field(default_factory=list)
    estimated_complexity: str = "moderate"  # simple | moderate | complex

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_id": self.task_id,
            "description": self.description,
            "dependencies": self.dependencies,
            "context_refs": self.context_refs,
            "estimated_complexity": self.estimated_complexity,
        }


@dataclass
class SubTaskResult:
    """Result from a sub-agent's execution of a SubTask."""

    task_id: str
    status: TaskStatus
    output: str
    error: str | None = None


SPLIT_SYSTEM_PROMPT = """You are a task analysis assistant. Given a user request, determine if it should be split into independent sub-tasks for parallel execution.

Rules:
- Only split if the request involves multiple INDEPENDENT pieces of work
- Each sub-task must be independently verifiable
- Maximum 5 sub-tasks
- If the request is simple or tightly coupled, return an empty list

Context-centric decomposition (CRITICAL):
- Split by CONTEXT BOUNDARIES, not by problem type
- DO NOT split into "code writer" and "test writer" — keep implementation + tests together
- DO NOT split tightly coupled components that need shared state
- Only split when context can be truly isolated (e.g., independent modules, separate research paths)
- Each sub-task should be a self-contained unit of work

Respond with JSON only:
{"subtasks": [{"description": "...", "dependencies": [], "complexity": "simple|moderate|complex"}]}
If no split needed: {"subtasks": []}"""


MERGE_SYSTEM_PROMPT = """You are a result aggregation assistant. Given multiple sub-task results, create a unified summary response.
Combine the outputs coherently. If any sub-task failed, note it but include successful results."""


class TaskSplitter:
    """Analyzes user requests and splits them into parallelizable sub-tasks."""

    def __init__(
        self, *, api_client: SupportsStreamingMessages, model: str
    ) -> None:
        self._api_client = api_client
        self._model = model

    async def analyze_and_split(
        self,
        user_request: str,
        context: SharedContext | None = None,
    ) -> list[SubTask]:
        """Analyze a request and return sub-tasks if splitting is beneficial."""
        prompt = f"Analyze this request and determine if it should be split:\n\n{user_request}"
        if context:
            messages = context.get_messages(max_count=5)
            if messages:
                history = "\n".join(
                    m.text for m in messages if m.text
                )
                prompt = f"Recent context:\n{history}\n\n{prompt}"

        request = ApiMessageRequest(
            model=self._model,
            messages=[ConversationMessage.from_user_text(prompt)],
            system_prompt=SPLIT_SYSTEM_PROMPT,
            max_tokens=1024,
        )

        collected = ""
        async for event in self._api_client.stream_message(request):
            from openharness.api.client import ApiTextDeltaEvent, ApiMessageCompleteEvent
            if isinstance(event, ApiTextDeltaEvent):
                collected += event.text
            elif isinstance(event, ApiMessageCompleteEvent):
                if event.message.text:
                    collected = event.message.text

        return self._parse_split_response(collected)

    def _parse_split_response(self, response: str) -> list[SubTask]:
        """Parse the LLM's JSON response into SubTask objects."""
        try:
            # Extract JSON from response (handle markdown code blocks)
            text = response.strip()
            if "```" in text:
                text = text.split("```")[1]
                if text.startswith("json"):
                    text = text[4:]
                text = text.strip()
            data = json.loads(text)
        except (json.JSONDecodeError, IndexError):
            return []

        subtasks: list[SubTask] = []
        for item in data.get("subtasks", []):
            if not isinstance(item, dict) or not item.get("description"):
                continue
            subtasks.append(SubTask(
                description=item["description"],
                dependencies=item.get("dependencies", []),
                estimated_complexity=item.get("complexity", "moderate"),
            ))
        return subtasks[:5]  # Enforce max 5

    async def merge_results(
        self,
        subtasks: list[SubTask],
        results: list[SubTaskResult],
    ) -> str:
        """Merge sub-task results into a unified response."""
        parts: list[str] = []
        for st, res in zip(subtasks, results):
            status = "completed" if res.status == TaskStatus.COMPLETED else "failed"
            parts.append(f"Task: {st.description}\nStatus: {status}\nOutput: {res.output}")
            if res.error:
                parts.append(f"Error: {res.error}")

        summary_prompt = "Merge these sub-task results:\n\n" + "\n---\n".join(parts)
        request = ApiMessageRequest(
            model=self._model,
            messages=[ConversationMessage.from_user_text(summary_prompt)],
            system_prompt=MERGE_SYSTEM_PROMPT,
            max_tokens=2048,
        )

        collected = ""
        async for event in self._api_client.stream_message(request):
            from openharness.api.client import ApiTextDeltaEvent, ApiMessageCompleteEvent
            if isinstance(event, ApiTextDeltaEvent):
                collected += event.text
            elif isinstance(event, ApiMessageCompleteEvent):
                if event.message.text:
                    collected = event.message.text

        return collected
